### ISSUE TITLE
Add proxy support for deploy.sh

### ISSUE THREAD

**Issue by trozet** [trozet/bgs_vagrant#8]
- Need to remove sudo commands from bootsrap.sh
- Detect proxy and add to bootsrap.sh, deploy
- Pass proxy into khaleesi and use environment + set proxy on role opnfv_install

**Comment by trozet** [comment]
Creating "proxy" branch to do this feature on

**Comment by pbandzi** [comment]
Hi Tim,

I am still trying to make it work behind proxy. Here is list of changes required so far.
- Vagrant file

```
config.vm.provision :shell, :inline => "export http_proxy=proxy_replace; export https_proxy=proxy_replace; export no_proxy=127.0.0.1,localhost,local,public_IP_of_vagrant_host>"
```

in vagrant host there is need to modify:

```
/etc/bashrc  -> same http_proxy and no_proxy vars have to be configured
/etc/yum.conf -> add proxy
```
- opnfv_ksgen_settings.yml

```
force-puppet: "true"
enable-puppetlabs-repo: "true"
http-proxy:proxy
http-proxy-port: number
```
- bootstrap.sh

before run.sh is executed following files has to be changed:
/opt/khaleesi/playbooks/opnfv.yml

```
- name: Install Foreman
  hosts: localhost
  gather_facts: True
  sudo: yes
  roles:
    - { role: foreman/opnfv-install }
  tags:
    - install
  environment:
    http_proxy: proxy:port
    https_proxy: proxy:port
```

/opt/khaleesi/roles/foreman/opnfv-install/tasks/main.yml

```
- name: Download vmlinuz
  get_url: url=http://mirror.centos.org/centos/7/os/x86_64/images/pxeboot/vmlinuz
           dest=/var/lib/tftpboot/boot/CentOS-7-x86_64-vmlinuz
           mode=644
           force=yes
           timeout=60
  environment:
    http_proxy: proxy:port
    https_proxy: proxy:port
```

there is need to be added --no-proxy opntion to wget command in kickstart provission template
